CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS item (
    id BIGINT GENERATED by default AS IDENTITY NOT NULL,
    name varchar(50) not null,
    description varchar(255),
    id_owner BIGINT references users (id),
    available boolean,
    CONSTRAINT pk_item PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS booking (
    id BIGINT GENERATED by default AS IDENTITY NOT NULL,
    item_id BIGINT references item (id),
    start_date TIMESTAMP WITHOUT TIME ZONE  not null ,
    end_date TIMESTAMP WITHOUT TIME ZONE  not null ,
    status VARCHAR(20),
    id_booker BIGINT references users (id),
    CONSTRAINT pk_booking PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS requests (
    id BIGINT GENERATED by default AS IDENTITY NOT NULL,
    description VARCHAR(255),
    requestor_id BIGINT references  users (id),
    CONSTRAINT pk_requests PRIMARY KEY (id)
                                    );

CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED by default AS IDENTITY NOT NULL,
    text varchar(255),
    item_id BIGINT references item(id),
    author_id BIGINT references users(id),
    created TIMESTAMP WITHOUT TIME ZONE  not null,
    CONSTRAINT pk_comments PRIMARY KEY (id)
                                   );

